#!/usr/bin/env python3
"""RLE-pack an iCE5 bitstream .bin into drivers/fpga_bitstream.h.

Usage: fpga_bitstream_pack.py <bitstream.bin> <output.h> [note]

Encoding (decoded by fpga_stream_bitstream() in drivers/fpga.c):
  ESC, ESC              -> one literal ESC byte
  ESC, value, count     -> `count` copies of `value` (4 <= count <= 255)
  anything else         -> literal byte
ESC is chosen per image as the least frequent byte value and emitted as
FPGA_BITSTREAM_RLE_ESC. The encoder round-trips the result before writing.
"""

import sys
from collections import Counter
from datetime import date

CHUNK = 4096          # flash array size; keeps individual objects small
RUN_MIN = 4
RUN_MAX = 255


def rle_encode(data: bytes, esc: int) -> bytes:
    out = bytearray()
    i = 0
    n = len(data)
    while i < n:
        j = i
        while j < n and data[j] == data[i] and j - i < RUN_MAX:
            j += 1
        run = j - i
        if run >= RUN_MIN:
            out += bytes((esc, data[i], run))
        else:
            for _ in range(run):
                if data[i] == esc:
                    out += bytes((esc, esc))
                else:
                    out.append(data[i])
        i = j
    return bytes(out)


def rle_decode(packed: bytes, esc: int) -> bytes:
    out = bytearray()
    i = 0
    while i < len(packed):
        b = packed[i]
        i += 1
        if b != esc:
            out.append(b)
        elif packed[i] == esc:
            out.append(esc)
            i += 1
        else:
            out += bytes([packed[i]]) * packed[i + 1]
            i += 2
    return bytes(out)


def main() -> None:
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    note = sys.argv[3] if len(sys.argv) > 3 else ""

    raw = open(src, "rb").read()
    esc = min(range(256), key=Counter(raw).__getitem__)
    packed = rle_encode(raw, esc)
    assert rle_decode(packed, esc) == raw, "round-trip failed"

    chunks = [packed[i:i + CHUNK] for i in range(0, len(packed), CHUNK)]

    with open(dst, "w") as f:
        w = f.write
        w(f"/* Auto-generated by tools/fpga_bitstream_pack.py from {src}"
          f" on {date.today()}. */\n")
        w("/* RLE-packed iCE5 SPI-slave configuration image."
          " Do not edit by hand. */\n")
        if note:
            w(f"/* {note} */\n")
        w("#ifndef FPGA_BITSTREAM_H\n#define FPGA_BITSTREAM_H\n\n")
        w('#include "utils.h"\n\n')
        w(f"#define FPGA_BITSTREAM_RAW_LEN {len(raw)}UL\n")
        w(f"#define FPGA_BITSTREAM_RLE_ESC 0x{esc:02X}u\n")
        w(f"#define FPGA_BITSTREAM_CHUNK_COUNT {len(chunks)}u\n\n")

        for ci, chunk in enumerate(chunks):
            w(f"static const __prog__ u8 __attribute__((space(prog))) "
              f"fpga_bitstream_{ci:02d}[{len(chunk)}u] = {{\n")
            for i in range(0, len(chunk), 12):
                row = ", ".join(f"0x{b:02X}u" for b in chunk[i:i + 12])
                w(f"    {row},\n")
            w("};\n\n")

        w("static const __prog__ u8 * const "
          "FPGA_BITSTREAM_CHUNKS[FPGA_BITSTREAM_CHUNK_COUNT] = {\n")
        for ci in range(len(chunks)):
            w(f"    fpga_bitstream_{ci:02d},\n")
        w("};\n\n")
        w("static const u16 "
          "FPGA_BITSTREAM_CHUNK_LEN[FPGA_BITSTREAM_CHUNK_COUNT] = {\n")
        for chunk in chunks:
            w(f"    {len(chunk)}u,\n")
        w("};\n\n#endif /* FPGA_BITSTREAM_H */\n")

    print(f"{src}: {len(raw)} -> {len(packed)} bytes "
          f"({len(packed) / len(raw) * 100:.1f}%), esc=0x{esc:02X}, "
          f"{len(chunks)} chunk(s)")


if __name__ == "__main__":
    main()
